version: '3'
services:
  dev:
    build: '.'
    container_name: devops-sandbox
    security_opt:
      - seccomp:unconfined
    ports:
        - "127.0.0.1:8889:8888"
    volumes:
      - ../../../../.:/docker
    working_dir: /docker